/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import implementacion.ArchivosEntrada;
import implementacion.GeneradorGraphviz;
import implementacion.EstructuraGeneral;
import static implementacion.Main.archivosEntrada;
import static implementacion.Main.estructuraGeneral;
import static implementacion.Main.interfaz;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author erikssonherlo
 */
public class CargarArchivos extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
   // private EstructuraGeneral estructuraGeneral;
    //private ArchivosEntrada archivosEntrada;
    //private GeneradorGraphviz graficador;
    public CargarArchivos() {
        initComponents();
        //this.estructuraGeneral = new EstructuraGeneral();
        //this.archivosEntrada = new ArchivosEntrada();
        //this.graficador = new GeneradorGraphviz();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargarImagenes = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        cargarCapas = new javax.swing.JButton();
        cargarUsuarios = new javax.swing.JButton();
        menuAnterior = new javax.swing.JButton();
        informacionImagenes = new javax.swing.JLabel();
        informacionUsuarios = new javax.swing.JLabel();
        informacionCapas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(850, 700));
        setSize(new java.awt.Dimension(850, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarImagenes.setBackground(new java.awt.Color(43, 46, 46));
        cargarImagenes.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cargarImagenes.setForeground(new java.awt.Color(250, 250, 244));
        cargarImagenes.setText("Cargar Imagenes");
        cargarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImagenesActionPerformed(evt);
            }
        });
        getContentPane().add(cargarImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 40));

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 40)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("GENERADOR DE IMAGENES");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 590, 53));

        Salir.setBackground(new java.awt.Color(43, 46, 46));
        Salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Salir.setForeground(new java.awt.Color(250, 250, 244));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 230, 40));

        cargarCapas.setBackground(new java.awt.Color(43, 46, 46));
        cargarCapas.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cargarCapas.setForeground(new java.awt.Color(250, 250, 244));
        cargarCapas.setText("Cargar Capas");
        cargarCapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarCapasActionPerformed(evt);
            }
        });
        getContentPane().add(cargarCapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 230, 40));

        cargarUsuarios.setBackground(new java.awt.Color(43, 46, 46));
        cargarUsuarios.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cargarUsuarios.setForeground(new java.awt.Color(250, 250, 244));
        cargarUsuarios.setText("Cargar Usuarios");
        cargarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(cargarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 230, 40));

        menuAnterior.setBackground(new java.awt.Color(43, 46, 46));
        menuAnterior.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        menuAnterior.setForeground(new java.awt.Color(250, 250, 244));
        menuAnterior.setText("Regresar al Menu Inicial");
        menuAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(menuAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 230, 40));

        informacionImagenes.setText("prueba");
        getContentPane().add(informacionImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 360, 40));

        informacionUsuarios.setText("prueba");
        getContentPane().add(informacionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 360, 40));

        informacionCapas.setText("prueba");
        getContentPane().add(informacionCapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 360, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImagenesActionPerformed
        
       // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        //Indicamos que solo podemos seleccionar archivos
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //Indicamos el filtro .form
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.im", "im");
        fileChooser.setFileFilter(filtro);
        //Abrimos el file chooser
        int comprobante = fileChooser.showOpenDialog(fileChooser);
        if(comprobante == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
             informacionImagenes.setText("El Archivo seleccionado fue: "+ archivo.getName());
          
            archivosEntrada.entradaArchivoImagenes(archivo, estructuraGeneral.getListaImagenes(), estructuraGeneral.getArbolCapas());
        } else {
            informacionImagenes.setText("Error al seleccionar el archivo a importar\n");
        }
      
    }//GEN-LAST:event_cargarImagenesActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void cargarCapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarCapasActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.cap", "cap");
        fileChooser.setFileFilter(filtro);
        //Abrimos el file chooser
        int comprobante = fileChooser.showOpenDialog(fileChooser);
        if(comprobante == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            informacionCapas.setText("El Archivo seleccionado fue: "+ archivo.getName());
           
            //Enviamos a analizar el archivo a importar
           
            archivosEntrada.entradaArchivoCapas(archivo, estructuraGeneral.getArbolCapas());
            
        } else {
            informacionCapas.setText("Error al seleccionar el archivo a importar\n");
            
        }

    }//GEN-LAST:event_cargarCapasActionPerformed

    private void cargarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarUsuariosActionPerformed
         JFileChooser fileChooser = new JFileChooser();
        //Indicamos que solo podemos seleccionar archivos
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //Indicamos el filtro .form
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.usr", "usr");
        fileChooser.setFileFilter(filtro);
        //Abrimos el file chooser
        int comprobante = fileChooser.showOpenDialog(fileChooser);
        if(comprobante == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            informacionUsuarios.setText("El Archivo seleccionado fue: "+ archivo.getName());
            
            archivosEntrada.entradaArchivoUsuarios(archivo, estructuraGeneral.getArbolUsuarios(), estructuraGeneral.getListaImagenes());
        } else {
            informacionUsuarios.setText("Error al seleccionar el archivo a importar\n");
        }
    }//GEN-LAST:event_cargarUsuariosActionPerformed

    private void menuAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnteriorActionPerformed
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton cargarCapas;
    private javax.swing.JButton cargarImagenes;
    private javax.swing.JButton cargarUsuarios;
    private javax.swing.JLabel informacionCapas;
    private javax.swing.JLabel informacionImagenes;
    private javax.swing.JLabel informacionUsuarios;
    private javax.swing.JButton menuAnterior;
    // End of variables declaration//GEN-END:variables
}
