/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static implementacion.EstructuraGeneral.interfaz;
import javax.swing.JOptionPane;

/**
 *
 * @author erikssonherlo
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        crearUsuario = new javax.swing.JButton();
        menuInicial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        codigoUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 40)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("GENERADOR DE IMAGENES");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 590, 53));

        Salir.setBackground(new java.awt.Color(43, 46, 46));
        Salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Salir.setForeground(new java.awt.Color(250, 250, 244));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 230, 40));

        crearUsuario.setBackground(new java.awt.Color(43, 46, 46));
        crearUsuario.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        crearUsuario.setForeground(new java.awt.Color(250, 250, 244));
        crearUsuario.setText("Crear Usuario");
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, 40));

        menuInicial.setBackground(new java.awt.Color(43, 46, 46));
        menuInicial.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        menuInicial.setForeground(new java.awt.Color(250, 250, 244));
        menuInicial.setText("Volver al Menu Inicial");
        menuInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicialActionPerformed(evt);
            }
        });
        getContentPane().add(menuInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 230, 40));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel1.setText("Codigo: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 90, 30));
        getContentPane().add(codigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void menuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicialActionPerformed
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuInicialActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField codigoUsuario;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton menuInicial;
    // End of variables declaration//GEN-END:variables
}
