/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static implementacion.Main.interfazCRUDUsuarios;
import static implementacion.Main.interfazCargaArchivos;
import static implementacion.Main.interfazGraphviz;
import static implementacion.Main.interfazImagenes;
import javax.swing.JOptionPane;

/**
 *
 * @author erikssonherlo
 */
public class InterfazInicial extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    public InterfazInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargarArchivos = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        usuarios = new javax.swing.JButton();
        crearImagenes = new javax.swing.JButton();
        graficarEstructuras = new javax.swing.JButton();
        generarImagenes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(650, 450));
        setSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarArchivos.setBackground(new java.awt.Color(43, 46, 46));
        cargarArchivos.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cargarArchivos.setForeground(new java.awt.Color(250, 250, 244));
        cargarArchivos.setText("Carga de Archivos");
        cargarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivosActionPerformed(evt);
            }
        });
        getContentPane().add(cargarArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 230, 40));

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 40)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("GENERADOR DE IMAGENES");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 590, 53));

        Salir.setBackground(new java.awt.Color(43, 46, 46));
        Salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Salir.setForeground(new java.awt.Color(250, 250, 244));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 230, 40));

        usuarios.setBackground(new java.awt.Color(43, 46, 46));
        usuarios.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        usuarios.setForeground(new java.awt.Color(250, 250, 244));
        usuarios.setText("Usuarios");
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 230, 40));

        crearImagenes.setBackground(new java.awt.Color(43, 46, 46));
        crearImagenes.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        crearImagenes.setForeground(new java.awt.Color(250, 250, 244));
        crearImagenes.setText("Crear Imagenes");
        crearImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearImagenesActionPerformed(evt);
            }
        });
        getContentPane().add(crearImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, 40));

        graficarEstructuras.setBackground(new java.awt.Color(43, 46, 46));
        graficarEstructuras.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        graficarEstructuras.setForeground(new java.awt.Color(250, 250, 244));
        graficarEstructuras.setText("Graficar Estructuras");
        graficarEstructuras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarEstructurasActionPerformed(evt);
            }
        });
        getContentPane().add(graficarEstructuras, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 230, 40));

        generarImagenes.setBackground(new java.awt.Color(43, 46, 46));
        generarImagenes.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        generarImagenes.setForeground(new java.awt.Color(250, 250, 244));
        generarImagenes.setText("Generar Imagenes");
        generarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarImagenesActionPerformed(evt);
            }
        });
        getContentPane().add(generarImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivosActionPerformed
        // TODO add your handling code here:
        
        interfazCargaArchivos.setVisible(true);
        this.setVisible(false);
     
    }//GEN-LAST:event_cargarArchivosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        interfazCRUDUsuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_usuariosActionPerformed

    private void crearImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearImagenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearImagenesActionPerformed

    private void graficarEstructurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarEstructurasActionPerformed
        interfazGraphviz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_graficarEstructurasActionPerformed

    private void generarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarImagenesActionPerformed
        interfazImagenes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_generarImagenesActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton cargarArchivos;
    private javax.swing.JButton crearImagenes;
    private javax.swing.JButton generarImagenes;
    private javax.swing.JButton graficarEstructuras;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
